version: '3.6'

services:
  app:
    container_name: wimf-app
    build:
      context: ../..
      dockerfile: .docker/Dockerfile
    image: wimf
#    manage.py search_index --rebuild
    command:
      - sh
      - "-c"
      - |
        /app/wait-for-it.sh postgres:5432
        python manage.py migrate
        /app/wait-for-it.sh elasticsearch:9200
        python manage.py loaddata seed_data/latest.json
        python manage.py collectstatic --noinput
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - ../..:/app
    environment:
      - DJANGO_LOCAL=0
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ES_USER=${ES_USER}
      - ES_PASSWORD=${ES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - elasticsearch
      - db
    links:
      - db:postgres

  db:
    container_name: wimf-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - wimf-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata:
    driver: local
  wimf-pgdata:
    driver: local
