"""
Django settings for wimf project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from wimf.settings import *

ELASTICSEARCH_DSL = {
    "default": {"hosts": "test-elasticsearch:9200"},
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("TEST_DATABASE_NAME", "test"),
        "USER": os.environ.get("TEST_DATABASE_USER", ""),
        "PASSWORD": os.environ.get("TEST_DATABASE_PASSWORD", ""),
        "HOST": "postgres",
        "PORT": "5432",
    },
}
