# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'db_table': 'recipe',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
