# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='cheese', max_length=2000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
